services:
  - type: web
    name: c2c-backend
    env: node
    buildCommand: npm install --include=dev && npx prisma generate && npm run build && ls -la dist/
    startCommand: npx prisma migrate deploy && node dist/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
